language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"

# Enable caching for pip to speed up builds by reusing previously downloaded packages
cache: pip

# Add PostgreSQL service for testing database interactions
services:
  - postgresql

# Environment variables for PostgreSQL
env:
  global:
    # Define a separate test database
    - POSTGRES_DB=labmate_test_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    # DATABASE_URL for the test database
    - TEST_DATABASE_URL=postgresql://postgres@localhost:5432/labmate_test_db

# Securely handle the DATABASE_URL using Travis CI's encrypted environment variables
# It's recommended to set DATABASE_URL in Travis CI's repository settings for security
# Alternatively, you can encrypt it using Travis CLI and add it here
# For example:
# - secure: "<encrypted_database_url>"

# Upgrade pip and setuptools before installation
before_install:
  - pip install --upgrade pip setuptools

# Install project dependencies and the project itself
install:
  - pip install -r requirements.txt
  - pip install .

# Set up the PostgreSQL database and run migrations
before_script:
  # Verify PostgreSQL installation
  - psql --version
  
  # Create the test database
  - psql -c 'CREATE DATABASE labmate_test_db;' -U postgres
  
  # Install flake8 for linting
  - pip install flake8
  
  # Run flake8 to ensure code style consistency
  - flake8 .  # This will fail the build if there are linting errors
  
  # Install Alembic for database migrations
  - pip install alembic
  
  # Run Alembic migrations to set up the test database schema
  # Ensure that alembic.ini is correctly configured to use TEST_DATABASE_URL for testing
  # Modify alembic.ini or env.py to switch DATABASE_URL based on environment variables if necessary
  - alembic upgrade head

# Run tests with coverage reporting
script:
  - pytest --cov=labmateai --cov-report=xml --cov-report=term-missing

# After successful tests, upload coverage reports to Codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Deployment configuration to PyPI
deploy:
  provider: pypi
  username: __token__  # Use '__token__' if deploying with an API token
  password:
    secure: "<pypi-AgEIcHlwaS5vcmcCJGFiZjdkNWY4LTFhZWUtNGRmZS04MWE2LWNlNGUyMWU4ZWJlMQACKlszLCJiYjI2YzRkMC1lZjA4LTRlZmMtOTZmMS0xMTkyNzFjZjM4ZmMiXQAABiATN_pxBDKC66Ol0lFe5jKB_FOdGeX4w93SY0qi9hY1cg>"
  on:
    tags: true  # Deploy only when a commit is tagged
    branch: collab_filtering  # Deploy only from the 'collab_filtering' branch
  distributions: "sdist bdist_wheel"  # Build both source and wheel distributions

# Email notifications for build results
notifications:
  email:
    recipients:
      - tnoblin@health.ucsd.edu
    on_success: change  # Notify only if the build status changes to success
    on_failure: always  # Always notify on failures